.\" Manpage for yadpass.
.\" Contact git@yeoldegrove.de to correct errors or typos.
.TH man 1 "04 Aug 2020" "1.0" "yadpass man page"
.SH NAME
yadpass \- little hacky GTK frontend for pass built using yad (a zenity clone)
.SH SYNOPSIS
yadpass
.SH DESCRIPTION
This is a little hacky GTK frontend for pass built using yad (a zenity clone).
It lets you query for passwords for your git cloned pass repository 
in ~/.password-store. The found entires can be clipboarded by wl-copy/xclip
or shown in cleartext on the screen.
It will work with X11 and Wayland and was initially designed for phosh on
pinephone and Librem 5.
.SH OPTIONS
yadpass does not take any options.
.SH SEE ALSO
pass(1), yad(1), xclip(1), wl-clipboard(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Eike Waldt (git@yeoldegrove.de)
